name = "refukus"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
routes = []
zone_id = ""

[env.production]
name = "refukus-production"
route = "YOUR_DOMAIN.com/*"
zone_id = "YOUR_ZONE_ID"

[build]
command = "npm run build"
cwd = "./"
watch_paths = []

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.txt", "**/*.html"]
fallthrough = true
